apiVersion: v2
name: pagopa-functions-template
description: Microservice description
type: application
version: 0.19.0
appVersion: 0.0.1-18-PAGOPA-2602-fdr-to-event-hub
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
