apiVersion: v2
name: pagopa-fdr-to-event-hub
description: Microservice fdr to event hub
type: application
version: 0.52.0
appVersion: 1.0.0-2-fix-fn-state
dependencies:
  - name: microservice-chart
    version: 7.1.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
