apiVersion: v2
name: pagopa-functions-template
description: Microservice description
type: application
version: 0.28.0
appVersion: 0.0.2-1-PAGOPA-2645-tuning-fdr-to-eventhub
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
