microservice-chart:
  namespace: "fdr"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-fdr-2-event-hub
    tag: "0.0.1-13-PAGOPA-2602-fdr-to-event-hub"
    pullPolicy: Always
  # https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  livenessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /info
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    port: 80
  ingress:
    create: true
    host: "weudev.fdr.internal.dev.platform.pagopa.it"
    path: /pagopa-fdr-to-event-hub-service/(.*)
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.25"
    limits:
      memory: "768Mi"
      cpu: "0.40"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    JAVA_OPTS: "-XX:MaxHeapSize=256m -XX:MinHeapSize=64m"
    WEBSITE_SITE_NAME: "pagopafdrtoeventhub" # required to show cloud role name in application insights
    FUNCTIONS_WORKER_RUNTIME: "java"
    BLOB_STORAGE_FDR1_CONTAINER: "fdr1-flows"
    BLOB_STORAGE_FDR3_CONTAINER: "fdr3-flows"
    EVENT_HUB_FLOWTX_NAME: "fdr-qi-flows"
    EVENT_HUB_REPORTEDIUV_NAME: "fdr-qi-reported-iuv"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: "ai-connection-string"
    FDR_SA_CONNECTION_STRING: "fdr-sa-connection-string"
    EVENT_HUB_REPORTEDIUV_CONNECTION_STRING: "fdr-qi-reported-iuv-tx-connection-string"
    EVENT_HUB_FLOWTX_CONNECTION_STRING: "fdr-qi-flows-tx-connection-string"
    AzureWebJobsStorage: "fdr-sa-connection-string"
  keyvault:
    name: "pagopa-d-fdr-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity: {}
  canaryDelivery:
    create: false
