microservice-chart:
  namespace: "fdr"
  nameOverride: "pagopa-fdr-2-event"
  fullnameOverride: "pagopa-fdr-2-event-hub"
  image:
    repository: ghcr.io/pagopa/pagopa-fdr-2-event-hub
    tag: "1.0.1-3-PAGOPA-2686"
    pullPolicy: Always
  # https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  # livenessProbe:
  #   httpGet:
  #     path: /info
  #     port: 80
  #   initialDelaySeconds: 60
  #   failureThreshold: 6
  #   periodSeconds: 10
  # readinessProbe:
  #   httpGet:
  #     path: /info
  #     port: 80
  #   initialDelaySeconds: 60
  #   failureThreshold: 6
  #   periodSeconds: 10
  livenessProbe:
    handlerType: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 10
  readinessProbe:
    handlerType: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 10
  deployment:
    create: true
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 12345 #jmx-exporter
    - 8080
  service:
    type: ClusterIP
    ports:
      - 8080
      - 12345 #jmx-exporter
  ingress:
    create: true
    host: "weuuat.fdr.internal.uat.platform.pagopa.it"
    path: /pagopa-fdr-to-event-hub-service/(.*)
    servicePort: 8080
  serviceAccount:
    name: "fdr-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "768Mi"
      cpu: "0.5"
    limits:
      memory: "4Gi"
      cpu: "3"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
      - type: memory
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    JAVA_OPTS: "-XX:MaxHeapSize=2304m -XX:MinHeapSize=256m"
    WEBSITE_SITE_NAME: "pagopafdrtoeventhub" # required to show cloud role name in application insights
    FUNCTIONS_WORKER_RUNTIME: "java"
    BLOB_STORAGE_FDR1_CONTAINER: "fdr1-flows"
    BLOB_STORAGE_FDR3_CONTAINER: "fdr3-flows"
    EVENT_HUB_FLOWTX_NAME: "fdr-qi-flows"
    EVENT_HUB_REPORTEDIUV_NAME: "fdr-qi-reported-iuv"
    ASPNETCORE_URLS: "http://*:8080"
    FUNCTIONS_SECRETS_PATH: "/tmp/secrets"
    AzureFunctionsWebHost__hostid: "fdr2eventhub"
  envFieldRef:
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: "ai-connection-string"
    FDR_SA_CONNECTION_STRING: "fdr-sa-connection-string"
    EVENT_HUB_REPORTEDIUV_CONNECTION_STRING: "fdr-qi-reported-iuv-tx-connection-string"
    EVENT_HUB_FLOWTX_CONNECTION_STRING: "fdr-qi-flows-tx-connection-string"
    AzureWebJobsStorage: "fdr-sa-connection-string"
  keyvault:
    name: "pagopa-u-fdr-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations:
    - key: dedicated
      operator: Equal
      value: "nodo"
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodo
                operator: In
                values:
                  - "true"
  canaryDelivery:
    create: false
